### ISSUE TITLE
[ReflectionException]

### ISSUE THREAD

**Issue by vintage51** [mlntn/lumen-artisan-serve#2]
Hello thanks for all your work in getting this done. I am having a slight issue. I have followed you steps and I keep getting a ReflectionException error.

Class Mlntn\Console\Commands\Serve::class, does not exist

I am not sure how to solve this problem. I can supply you with logs and versions if that will help.

Again thanks

Robert

**Comment by mlntn** [comment]
Sounds like an issue with your autoloader or maybe composer install didn't happen?

**Comment by vintage51** [comment]
I have looked at as much code as I can figure out. But I don't know php and composer. This error occurs when i run the php artisan serve

**Comment by vintage51** [comment]
I figured out that you need to run your composer command inside the apps root folder, correct.

**Comment by mlntn** [comment]
No, you should run it from where your composer.json file exists. This should be in the root directory.

**Comment by vintage51** [comment]
OK, Help me to understand.
1) I created a new lumen project (lumen new blog)
2) cd into the blog directory and run your composer command.
3) added your code into the Kernel.php 
4 ) got error when trying to run artisan serve

If I am really off base I apologize. That was the only way to get your code to show up in the vendors folder in the blog project.

**Comment by mlntn** [comment]
That's exactly what you should do, but something didn't work out right. I just tested locally and it worked.

```
[/var/www]$ lumen new blog
Crafting application...
Application ready! Build something amazing.
[/var/www]$ cd blog/
[/var/www/blog]$ composer require mlntn/lumen-artisan-serve "~1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mlntn/lumen-artisan-serve (1.1)
    Downloading: 100%

Writing lock file
Generating autoload files
[/var/www/blog]$ vi app/Console/Kernel.php
[/var/www/blog]$ artisan serve
Lumen development server started on http://localhost:8000/
```

Which version of PHP are you using? Can you share your composer.json?

**Comment by vintage51** [comment]
Testing again with a new project

**Comment by vintage51** [comment]
This is what I get:

[root@spare ~]# lumen new test
Crafting application...
Application ready! Build something amazing.
[root@spare ~]# cd test
[root@spare test]# composer require mlntn/lumen-artisan-serve "~1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing mlntn/lumen-artisan-serve (1.1)
  Downloading: 100%

Writing lock file
Generating autoload files
[root@spare test]# nano app/Console/Kernel.php
[root@spare test]# php artisan serve

  [ReflectionException]
  Class Mlntn\Console\Commands\Serve::class, does not exist

[root@spare test]#

**Comment by vintage51** [comment]
This is what composer has installed

installed:
  doctrine/inflector                v1.1.0  Common String Manipulations with regard to casing and singular/plural ru...
  doctrine/instantiator             1.0.5   A small, lightweight utility to instantiate objects in PHP without invok...
  fzaninotto/faker                  v1.5.0  Faker is a PHP library that generates fake data for you.
  illuminate/auth                   v5.2.19 The Illuminate Auth package.
  illuminate/broadcasting           v5.2.19 The Illuminate Broadcasting package.
  illuminate/bus                    v5.2.19 The Illuminate Bus package.
  illuminate/cache                  v5.2.19 The Illuminate Cache package.
  illuminate/config                 v5.2.19 The Illuminate Config package.
  illuminate/console                v5.2.19 The Illuminate Console package.
  illuminate/container              v5.2.19 The Illuminate Container package.
  illuminate/contracts              v5.2.19 The Illuminate Contracts package.
  illuminate/database               v5.2.19 The Illuminate Database package.
  illuminate/encryption             v5.2.19 The Illuminate Encryption package.
  illuminate/events                 v5.2.19 The Illuminate Events package.
  illuminate/filesystem             v5.2.19 The Illuminate Filesystem package.
  illuminate/hashing                v5.2.19 The Illuminate Hashing package.
  illuminate/http                   v5.2.19 The Illuminate Http package.
  illuminate/pagination             v5.2.19 The Illuminate Pagination package.
  illuminate/pipeline               v5.2.19 The Illuminate Pipeline package.
  illuminate/queue                  v5.2.19 The Illuminate Queue package.
  illuminate/session                v5.2.19 The Illuminate Session package.
  illuminate/support                v5.2.19 The Illuminate Support package.
  illuminate/translation            v5.2.19 The Illuminate Translation package.
  illuminate/validation             v5.2.19 The Illuminate Validation package.
  illuminate/view                   v5.2.19 The Illuminate View package.
  laravel/lumen-framework           v5.2.5  The Laravel Lumen Framework.
  mlntn/lumen-artisan-serve         1.1     artisan serve for Lumen projects
  monolog/monolog                   1.17.2  Sends your logs to files, sockets, inboxes, databases and various web se...
  mtdowling/cron-expression         v1.1.0  CRON for PHP: Calculate the next or previous run date and determine if a...
  nesbot/carbon                     1.21.0  A simple API extension for DateTime.
  nikic/fast-route                  v0.7.0  Fast request router for PHP
  paragonie/random_compat           v1.2.0  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
  phpdocumentor/reflection-docblock 2.0.4
  phpspec/prophecy                  v1.6.0  Highly opinionated mocking framework for PHP 5.3+
  phpunit/php-code-coverage         2.2.4   Library that provides collection, processing, and rendering functionalit...
  phpunit/php-file-iterator         1.4.1   FilterIterator implementation that filters files based on a list of suff...
  phpunit/php-text-template         1.2.1   Simple template engine.
  phpunit/php-timer                 1.0.7   Utility class for timing
  phpunit/php-token-stream          1.4.8   Wrapper around PHP's tokenizer extension.
  phpunit/phpunit                   4.8.23  The PHP Unit Testing framework.
  phpunit/phpunit-mock-objects      2.3.8   Mock Object library for PHPUnit
  psr/log                           1.0.0   Common interface for logging libraries
  sebastian/comparator              1.2.0   Provides the functionality to compare PHP values for equality
  sebastian/diff                    1.4.1   Diff implementation
  sebastian/environment             1.3.3   Provides functionality to handle HHVM/PHP environments
  sebastian/exporter                1.2.1   Provides the functionality to export PHP variables for visualization
  sebastian/global-state            1.1.1   Snapshotting of global state
  sebastian/recursion-context       1.0.2   Provides functionality to recursively process PHP variables
  sebastian/version                 1.0.6   Library that helps with managing the version number of Git-hosted PHP pr...
  symfony/console                   v3.0.2  Symfony Console Component
  symfony/debug                     v3.0.2  Symfony Debug Component
  symfony/event-dispatcher          v3.0.2  Symfony EventDispatcher Component
  symfony/finder                    v3.0.2  Symfony Finder Component
  symfony/http-foundation           v3.0.2  Symfony HttpFoundation Component
  symfony/http-kernel               v3.0.2  Symfony HttpKernel Component
  symfony/polyfill-mbstring         v1.1.0  Symfony polyfill for the Mbstring extension
  symfony/polyfill-php56            v1.1.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
  symfony/polyfill-util             v1.1.0  Symfony utilities for portability of PHP codes
  symfony/process                   v3.0.2  Symfony Process Component
  symfony/translation               v3.0.2  Symfony Translation Component
  symfony/yaml                      v3.0.2  Symfony Yaml Component
  vlucas/phpdotenv                  v2.2.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SE...

**Comment by vintage51** [comment]
My php version

[root@spare test]# php -v
PHP 5.6.18 (cli) (built: Feb  4 2016 22:08:11)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
[root@spare test]#

**Comment by vintage51** [comment]
[root@spare test]# cat composer.json
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.2.*",
        "vlucas/phpdotenv": "~2.2",
        "mlntn/lumen-artisan-serve": "~1"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~4.0"
    },
    "autoload": {
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    }
}
[root@spare test]#

**Comment by vintage51** [comment]
question are you running under homestead? I did a manual install of Lumen on a Centos 7 server.

**Comment by mlntn** [comment]
I'm just running locally. OS and version _shouldn't_ matter.

Can you send me a copy of your Kernel.php? I have a hunch on what the issue is.

**Comment by vintage51** [comment]
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Laravel\Lumen\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     \* The Artisan commands provided by your application.
     *
     \* @var array
     */
    protected $commands = [
        '\Mlntn\Console\Commands\Serve::class,'
    ];

```
/**
 * Define the application's command schedule.
 *
 * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
 * @return void
 */
protected function schedule(Schedule $schedule)
{
    //
}
```

}

**Comment by mlntn** [comment]
Yep, my hunch was right. The reference to the class in enclosed in quotes. It should be:

```
protected $commands = [
  \Mlntn\Console\Commands\Serve::class,
];
```

**Comment by vintage51** [comment]
OK will try without quotes

**Comment by vintage51** [comment]
You got it !!!!. Not sure where I got the idea that it needed quotes. Thanks so much for your help and also getting this to work.

Robert

**Comment by mlntn** [comment]
No problem! Now go make something awesome with Lumen. :)

**Comment by vintage51** [comment]
I will have a Great Day!!!!
