### ISSUE TITLE
Error : Directory 'E:\www\lumen\public' does not exist

### ISSUE THREAD

**Issue by xushuhui** [mlntn/lumen-artisan-serve#7]
Hello thanks for all your working . I am having a issue.  It is  error "Directory 'E:\www\lumen\public' does not exist"  in project when I use it in my lumen projects , the develop environment is windows 10. php 7.2

I am  solve this problem.  the reason is Serve.php line 57
` passthru("{$binary} -S {$host}:{$port} -t '{$docroot}' {$base}/server.php");`

the '{$docroot}' as 'xxx' string  be execute. It is normal when remove  apostrophe
such as
` passthru("{$binary} -S {$host}:{$port} -t {$docroot} {$base}/server.php");`

Again thanks

**Comment by Cryental** [comment]
Bug fixed version is available here: 
composer require cryental/lumen-artisan-serve

Confirmed with Lumen 8.x

**Comment by mlntn** [comment]
@Cryental Do you want to submit a pull request with your fix?

**Comment by Cryental** [comment]
Sure! Done :)
It was a simple syntax mistake :P

**Comment by mlntn** [comment]
Thanks!

**Comment by Cryental** [comment]
Please don't forget to create a package so I can change to your composer link again :)

**Comment by mlntn** [comment]
Done.

**Comment by Cryental** [comment]
Thank you but you didn't update on the composer side :)
Root composer.json requires mlntn/lumen-artisan-serve ^1.4, found mlntn/lumen-artisan-serve[dev-master, 1.0, 1.1, 1.2, 1.3] but it does not match the constraint.
